/** @format */
export const AXIOSINSTANCE = "AXIOSINSTANCE";
export const AXIOSINSTANCE_SERVER_URL = "AXIOSINSTANCE_SERVER_URL";
export const AXIOSINSTANCE_TOKEN = "AXIOSINSTANCE_TOKEN";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SETEMAIL = "SETEMAIL";
export const SETNAME = "SETNAME";
export const SETPASSWORD = "SETPASSWORD";
export const SETADMINKEY = "SETADMINKEY";

export const ALLCOUNTRIES = "ALLCOUNTIES";
export const COUNTRYBYID = "COUNTRYBYID";

export const ALLCITIES = "ALLCITIES";
export const CITYBYID = "CITYBYID";
export const FINDEDCITIES = "FINDEDCITIES";

export const ALLAIRPORTS = "ALLAIRPORTS";
export const AIRPORTBYID = "AIRPORTBYID";

export const CREATECLASSFLIGHT = "CREATECLASSFLIGHT";
export const GETALLCLASSESFLIGHT = "GETALLCLASSESFLIGHT";

export const CLEAN_QUERY = "CLEAN_QUERY";
export const START_SEARCH = "START_SEARCH";
export const FINISH_SEARCH_FROM = "FINISH_SEARCH_FROM";
export const FINISH_SEARCH_TO = "FINISH_SEARCH_TO";

export const UPDATE_SELECTION_FROM = "UPDATE_SELECTION_FROM";
export const UPDATE_SELECTION_TO = "UPDATE_SELECTION_TO";

export const CITY_O_D = "CITY_O_D";
export const COUNTRY = "COUNTRY";
export const AIRPORTS = "AIRPORTS";
export const FINDEDAIRPORTS = "FINDEDAIRPORTS";
export const FLIGHTS = "FLIGHTS";
export const ADDCITY = "ADDCITY";
export const CITY_AIRPORT = "CITY_AIRPORT";

export const SAVEFLIGHT = "SAVEFLIGHT";
// export const ABOUT = "ABOUT"

export const SEARCH = "SEARCH";
